Realty7/Areas/eng/Controllers/OurAgentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Realty7.Models;

namespace Realty7.Areas.eng.Controllers
{
    public class OurAgentsController : Controller
    {
        //
        // GET: /eng/OurAgents/

        public ActionResult Index(int? page, string sort)
        {
            AgentViewModel avm = new AgentViewModel();
            avm.GetAgents(page, sort);
            return View(avm);
        }

    }
}

Realty7/Areas/eng/Controllers/QAController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Configuration;

namespace Realty7.Areas.eng.Controllers
{
    public class QAController : Controller
    {
        //
        // GET: /eng/QA/

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(string FirstName, string LastName, string Email, string Phone, string Comments)
        {
            using (MailMessage mail = new MailMessage())
            {

                    var to = WebConfigurationManager.AppSettings["ToEmail"].ToString();
                    var from = Email;
                    var fromName = FirstName + " " + LastName;
                    var subject = "REALTY7.COM - MESSAGE FROM " + FirstName + " " + LastName;
                try
                {
                    StringBuilder msg = new StringBuilder();
                    msg.Append("REALTY7.COM :: Automated Message Delivery\n\n");
                    msg.Append("First Name: " + FirstName + "\n");
                    msg.Append("Last Name: " + LastName + "\n");
                    msg.Append("Email Address: " + Email + "\n");
                    msg.Append("Comments/Questions:\n");
                    msg.Append(Comments);

                    SmtpClient SmtpServer = new SmtpClient("mail.sonyachoi.com");
                    mail.From = new MailAddress(from);
                    mail.To.Add(to);
                    mail.Subject = subject;
                    mail.Body = msg.ToString();
                    SmtpServer.Port = 25;
                    SmtpServer.Credentials = new System.Net.NetworkCredential("info@sonyachoi.com", "sunhwa1986");
                    //SmtpServer.EnableSsl = true;
                    SmtpServer.Send(mail);
                    ViewBag.Message = "Thank you " + FirstName + " " + LastName + "! We will be in touch with you shortly.";
                }
                catch (Exception e)
                {
                    ViewBag.Message = "We're sorry. The message failed to be sent. Please email us directly at <a href='mailto:"+to+ "'>" + to + "</a>.";
                    throw e;
                }
            }        
            return View();
        }

    }
}

Realty7/Areas/kor/Controllers/QAController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Configuration;

namespace Realty7.Areas.kor.Controllers
{
    public class QAController : Controller
    {
        //
        // GET: /kor/QA/

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(string FirstName, string LastName, string Email, string Phone, string Comments)
        {
            using (MailMessage mail = new MailMessage())
            {

                var to = WebConfigurationManager.AppSettings["ToEmail"].ToString();
                var from = Email;
                var fromName = FirstName + " " + LastName;
                var subject = "REALTY7.COM - MESSAGE FROM " + FirstName + " " + LastName;
                try
                {
                    StringBuilder msg = new StringBuilder();
                    msg.Append("REALTY7.COM :: Automated Message Delivery\n\n");
                    msg.Append("First Name: " + FirstName + "\n");
                    msg.Append("Last Name: " + LastName + "\n");
                    msg.Append("Email Address: " + Email + "\n");
                    msg.Append("Comments/Questions:\n");
                    msg.Append(Comments);

                    SmtpClient SmtpServer = new SmtpClient("mail.sonyachoi.com");
                    mail.From = new MailAddress(from);
                    mail.To.Add(to);
                    mail.Subject = subject;
                    mail.Body = msg.ToString();
                    SmtpServer.Port = 25;
                    SmtpServer.Credentials = new System.Net.NetworkCredential("info@sonyachoi.com", "sunhwa1986");
                    //SmtpServer.EnableSsl = true;
                    SmtpServer.Send(mail);
                    ViewBag.Message = "Thank you " + FirstName + " " + LastName + "! We will be in touch with you shortly.";
                }
                catch (Exception e)
                {
                    ViewBag.Message = "We're sorry. The message failed to be sent. Please email us directly at <a href='mailto:" + to + "'>" + to + "</a>.";
                    throw e;
                }
            }
            return View();
        }
    }
}

Realty7/Areas/eng/Views/QA/Index.cshtml
@{
    ViewBag.Title = "Realty 7 LLC :: Q/A";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">
    $(function () {
        $("#qa").addClass("active");
    });
</script>
<script src="~/Scripts/validator.js"></script>
<style>
    #mobile-banner {
        width: 100%;
        height: auto;
    }

    .side-menu {
        margin: 10px 10px 10px 50px;
    }

    textarea {
        width: 350px;
        height: 150px;
    }
</style>
<div class="main">
    <img id="mobile-banner" src="~/Content/images/qa.jpg" class="img-responsive animated fadeIn" />
    <div class="row">

        <div class="col-md-3" id="pc-menu">
            <div class="side-menu">@Html.ActionLink("Realty 7 에이젼트 보기", "Index", "OurAgents", new { area = "kor" }, null)</div>
        </div>
        <div class="col-md-9" style="margin-top:10px">
            <div class="col-md-12" style="margin-top:10px">
                <b>Realty 7 LLC (Fort Lee Office)</b><br />
                2160 North Central Rd. Suite 207<br />
                Fort Lee, NJ 07024<br />
                Office: 201-292-7777<br />
                Fax: 201-482-0423<br />
                Email: jamesleerealty7@gmail.com
                <br /><br />Please contact us if you have any questions or comments. <br /><br />
            </div>
            <div class="col-md-12" style="margin-top:15px">
                <span class="thanks">@ViewBag.Message&nbsp;</span>
            </div>
            <div class="col-md-12">
                @using (Html.BeginForm(null, null, FormMethod.Post, new { name = "contact_form", id = "contact_form" }))
                { <div class="col-md-3">First Name</div><div class="col-md-9">@Html.TextBox("FirstName")<span class="required">*</span></div>
                <div class="col-md-3" style="margin-top:2px">Last Name</div><div class="col-md-9" style="margin-top:2px">@Html.TextBox("LastName")<span class="required">*</span></div>
                <div class="col-md-3" style="margin-top:2px">Email Address</div><div class="col-md-9" style="margin-top:2px">@Html.TextBox("Email")<span class="required">*</span></div>
                <div class="col-md-3" style="margin-top:2px">Phone Number</div><div class="col-md-9" style="margin-top:2px">@Html.TextBox("Phone")<span class="required">*</span></div>
                <div class="col-md-3" style="margin-top:10px">Your questions or comments</div><div class="col-md-9" style="margin-top:10px">@Html.TextArea("Comments")</div>
                <div class="col-md-3" style="margin-top:10px">&nbsp;</div><div class="col-md-9" style="margin-top:10px"><input type="submit" /></div>
                }
            </div>
            <script language="JavaScript" type="text/javascript">
                var chk = new Validator("contact_form");
                chk.addValidation("FirstName", "req", "Please enter your first name");
                chk.addValidation("LastName", "req", "Please enter you last name");
                chk.addValidation("Email", "req", "Please enter your email");
                chk.addValidation("Email", "email", "Please enter a valid email");
                chk.addValidation("Phone", "req", "Please enter your phone number");
            </script>
            <div class="col-md-12" style="margin-top:10px">
                Your privacy is important to us. Your information will not be sold or exchanged with anyone else. All information you provide will be kept strictly confidential.
            </div>
        </div>

    </div>
</div>
  