Realty7/Areas/eng/Controllers/SchoolInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Realty7.Areas.eng.Controllers
{
    public class SchoolInfoController : Controller
    {
        //
        // GET: /eng/SchoolInfo/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Realty7/Areas/eng/Controllers/TownInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Realty7.Areas.eng.Controllers
{
    public class TownInfoController : Controller
    {
        //
        // GET: /eng/TownInfo/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Realty7/Areas/eng/Controllers/TransportationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Realty7.Areas.eng.Controllers
{
    public class TransportationController : Controller
    {
        //
        // GET: /eng/Transportation/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Realty7/Areas/kor/Controllers/TownInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Realty7.Areas.kor.Controllers
{
    public class TownInfoController : Controller
    {
        //
        // GET: /kor/TownInfo/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Realty7/Areas/kor/Views/TownInfo/Index.cshtml
@{
    ViewBag.Title = "Realty 7 LLC :: Town Info";
    Layout = "~/Views/Shared/_LayoutKor.cshtml";
}


<script type="text/javascript">
    $(function () {
        $("#town-info").addClass("active");
        if (/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) {
            $("#pc-menu").hide();
        } else {
            $("#mobile-menu").hide();
        }
    });
</script>
<style>
    #mobile-banner {
        width: 100%;
        height: auto;
    }
    .side-menu {
        margin:10px 10px 10px 50px;
    }
</style>
<div class="main">
    <img id="mobile-banner" src="~/Content/images/info.jpg" class="img-responsive animated fadeIn" />

    <div class="row">

        <div class="col-md-3" style="border-right-style:solid; border-right-width:1px" id="pc-menu">
            <div class="side-menu">타운 소개</div>
            <div class="side-menu">@Html.ActionLink("학군 정보", "Index", "SchoolInfo")</div>
            <div class="side-menu">@Html.ActionLink("교통 정보", "Index", "Transportation")</div>
        </div>
        <div class="col-md-9" style="padding-top:10px; padding-left:60px">
            <div class="TownInfo">
                <div style="background-color:white">
                    <a href="http://www.njmls.com/communities/" target="_blank">
                        <img src="~/Content/images/NJMLS.png" /><br />
                        <b>Click Here</b>
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="row" id="mobile-menu" style="text-align:center">
        <div class="col-md-4">
            타운 소개
        </div>
        <div class="col-md-4">
            @Html.ActionLink("학군 정보", "Index", "SchoolInfo")
        </div>
        <div class="col-md-4">
            @Html.ActionLink("교통 정보", "Index", "Transportation")
        </div>
    </div>
</div>